stophabapp:
  image: busybox
  volumes:
    - /var/www/sh:/var/www/sh

stophabnode:
  build: ./node
  volumes_from:
    - stophabapp

stophabelastic:
  image: elasticsearch
  restart: always
  volumes:
    - /data/stophab/elasticsearch:/usr/share/elasticsearch/data
    - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

stophabphp:
  build: ./php
  restart: always
  links:
    - stophabelastic:elastic
  volumes_from:
    - stophabapp
  extra_hosts:
    - mysql:78.47.3.3

stophabnginx:
  image: nginx
  restart: always
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/stophab.conf:/etc/nginx/sites-enabled/stophab.conf
  volumes_from:
    - stophabapp
  links:
    - stophabphp:php
  ports:
    - "8080:80"